experiment:
  algorithm: dqn          # dqn | ppo | qlearning
  paradigm: 0             # 0=fixed start & goal
                           # 1=random start, fixed goal
                           # 2=random start & random goal
  seed: 42
  #seed 42 for testing it can learn 1 block movement

  training:
    episodes: 200
    max_steps: 500
    step_dt: 0.25

    checkpoint:
      enabled: true
      interval: 50

  federated:
    enabled: true
    aggregation:
      algorithm: FedAvg
      communication_rounds: 20
      local_episodes: 10
  lidar:
    sectors: 24

  goal:
    mode: random_per_run
    radius: 0.30

  reward:
    terminal:
      goal: 100
      collision: -100

    shaping:
      progress: 10.0
      heading: 0.5
      forward: 1.0
      turn_penalty: 0.05
      wall_distance: 0.40
      wall_penalty: 3.0
      time: 0.005

  collision:
    lidar_threshold: 0.15
    min_close_rays: 3
  algorithms:

    dqn:
      learning_rate: 0.001
      gamma: 0.99
      epsilon: 1.0
      epsilon_min: 0.05
      epsilon_decay: 0.995
      replay_buffer: 100000
      batch_size: 64
      target_update: 10

    ppo:
      learning_rate: 0.0003
      gamma: 0.99
      gae_lambda: 0.95
      clip: 0.20
      epochs: 10

    qlearning:
      learning_rate: 0.10
      gamma: 0.99
      epsilon: 1.0
      epsilon_min: 0.05
      epsilon_decay: 0.995

environment:
  maze:
    size: 6
    cell_size: 1.0

federated:
  enabled: false

  aggregation:
    algorithm: FedAvg
    communication_rounds: 100
    local_episodes: 10

logging:
  tensorboard: true
  csv: true

  log_dir: /root/catkin_ws/src/logs/training
  model_dir: /root/catkin_ws/src/models

robots:
  - name: robot1
    deploy: true

    spawn: [0.0, 0.0, 0.0]
    maze_spawn: [0.0, 0.0, 0.0]

    start: [-1.5, -1.5, 0.0]
    goal: [-1.5, 2.5, 0.0]

    linear_speed: 0.25
    angular_speed: 1.0

    loggers:
      - odom
      - lidar
      - velocity

  - name: robot2
    deploy: true

    spawn: [7.0, 0.0, 0.0]
    maze_spawn: [7.0, 0.0, 0.0]

    start: [5.5, -1.5, 0.0]
    goal: [5.5, 2.5, 0.0]

    linear_speed: 0.25
    angular_speed: 1.0

    loggers:
      - odom
      - lidar
      - velocity

  - name: robot3
    deploy: true

    spawn: [0.0, 7.0, 0.0]
    maze_spawn: [0.0, 7.0, 0.0]

    start: [-1.5, 5.5, 0.0]
    goal: [1.5, 5.5, 0.0]

    linear_speed: 0.25
    angular_speed: 1.0

    loggers:
      - odom
      - lidar
      - velocity